version: '3'

# Refrence: https://stackoverflow.com/a/53418591

services:

  # laradock:
  #   build:
  #     context: .
  #   image: sujaykumarh/laradock:1.1

  laradock-latest:
    build:
      context: ./default
    image: sujaykumarh/laradock:latest

  laradock-ffmpeg:
    build:
      context: ./ffmpeg
    image: sujaykumarh/laradock:ffmpeg
    depends_on:
      - laradock-latest