#!/bin/sh

####
## AiO (All in one) artisan optimize
##
## MIT license   : Copyright (c) 2024 sujaykumarh 
## Full license : https://github.com/sujaykumarh/laradock/blob/main/LICENSE
####

if [ -f 'artisan' ]; then

    # Helper function to check and run artisan commands
    run_if_exists() {
        # Usage: run_if_exists "command:name"
        if php artisan list | grep -q "$1"; then
            php artisan "$1"
        else
            echo "Skipping: Command '$1' is not available."
        fi
    }

    # Standard commands
    # php artisan optimize
    
    # Optional / Package-specific commands
    run_if_exists "filament:optimize"

    # Final optimization
    php artisan optimize

else
    echo "artisan file not found in path!"
    exit 1
fi