#!/bin/sh

if [ -f 'artisan' ]; then

    php artisan clear-compiled
    php artisan cache:clear
    php artisan config:clear
    # php artisan debugbar:clear
    php artisan view:clear
    php artisan optimize

else
    echo "artisan file not found in path!"
    exit 1
fi
