name: "Build & Publish Docker Image"

# trigger events
on:
  # Manual
  workflow_dispatch:

  # automatic
  push:
    branches:
      - 'main'
    paths:
      - "Dockerfile"
      - ".docker/**"

jobs:

  # Generate Docker image
  build-push:
    name: build-docker-image
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:

      # Pull Source Code
      -
        name: Checkout
        uses: actions/checkout@v4

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker for Buildx env
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - run: echo BUILD_INFO="$(date +%s)" >> $GITHUB_ENV
      # - run: echo BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      # ## Login
      # - name: 🔐 Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.dockerHubUsername }}
      #     password: ${{ secrets.dockerHubPassword }}

      - name: 🔐 Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # build-args: |
          #   ARG LARAVEL_UID="1000"
          #   LARAVEL_GID="1000"
          #   LARAVEL_USER="laravel"
          #   LARAVEL_GROUP="laravel"
          #   LARAVEL_USERHOME="/home/laravel"
          #   LARAVEL_WORKDIR="/app"
          #   LARAVEL_APPDIR="/app"
          #   LARAVEL_DATADIR="/app/.data"
          #   PHP_EXT_INSTALLER_VER="latest"
      
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true